#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[[ -f $HOME/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources &

# picom &
#picom -b --unredir-if-possible --backend xr_glx_hybrid --vsync --use-damage --glx-no-stencil &

export DESKTOP_SESSION=plasma
exec startplasma-x11
