#!/bin/sh

# Xinit Xresources
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
[[ -f $HOME/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources &

# Plasma
export DESKTOP_SESSION=plasma

# Make kwin render at 144hz
export __GL_SYNC_DISPLAY_DEVICE=DP-0
export __GL_GSYNC_ALLOWED=0
export KWIN_X11_REFRESH_RATE=144000
export KWIN_X11_NO_SYNC_TO_VBLANK=1
export KWIN_X11_FORCE_SOFTWARE_VSYNC=1

# Hardware Acceleration
export LIBVA_DRIVER_NAME=nvidia
export VDPAU_DRIVER=nvidia

nvidia-settings -l &
exec startplasma-x11
