#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[[ -f $HOME/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources &

export DESKTOP_SESSION=plasma

# Vain attempts copied from the internet
# to get KWin to render at a higher framerate than 60.
__GL_SYNC_DISPLAY_DEVICE=DP-0
__GL_GSYNC_ALLOWED=0
KWIN_X11_REFRESH_RATE=288000
KWIN_X11_NO_SYNC_TO_VBLANK=1
KWIN_X11_FORCE_SOFTWARE_VSYNC=1

nvidia-settings -l &
exec startplasma-x11
